services:
    ystools_dtc.twig_extenstion.default_theme_configuration:
        class: 'YsTools\Bundle\DefaultThemeConfigurationBundle\Twig\DefaultThemeConfigurationExtension'
        public: false
        arguments:
            - '@oro_platform.twig.service_locator'
        tags:
            - { name: twig.extension }

    # data transformer is overridden to fix file upload issue
    oro_config.form.config_file_data_transformer:
        class: 'YsTools\Bundle\DefaultThemeConfigurationBundle\Form\DataTransformer\ConfigFileDataTransformer'
        arguments:
            - '@oro_entity.doctrine_helper'
            - '@validator'

    ystools_dtc.form_type.stylesheet:
        class: 'YsTools\Bundle\DefaultThemeConfigurationBundle\Form\Type\StylesheetType'
        tags:
            - { name: form.type, alias: ystools_stylesheet }
