liip_imagine:
    filter_sets:
        dtc_company_logo:
            quality:          95
            filters:
                relative_resize: { heighten: 50 }
                strip:        ~
        dtc_favicon:
            quality:          100
            filters:
                thumbnail: { size: [64, 64], mode: inset, allow_upscale: false }
                strip:        ~
