system_configuration:
    groups:
        dtc_default_theme_configuration:
            title: 'ystools.system_configuration.group.default_theme_configuration.label'
            icon:  fa-cog
        dtc_logo_configuration:
            title: 'ystools.system_configuration.group.logo_configuration.label'
        dtc_ui_main_element_color_configuration:
            title: 'ystools.system_configuration.group.ui_main_element_color_configuration.label'
        dtc_ui_secondary_element_color_configuration:
            title: 'ystools.system_configuration.group.ui_secondary_element_color_configuration.label'
        dtc_ui_menu_color_configuration:
            title: 'ystools.system_configuration.group.ui_menu_color_configuration.label'
        dtc_ui_button_color_configuration:
            title: 'ystools.system_configuration.group.ui_button_color_configuration.label'
        dtc_ui_additional_styling_configuration:
            title: 'ystools.system_configuration.group.ui_additional_styling_configuration.label'

    fields:
        ystools_dtc.company_logo:
            data_type: string
            type: 'Oro\Bundle\ConfigBundle\Form\Type\ConfigFileType'
            priority: 10
            options:
                label:      'ystools.system_configuration.field.company_logo.label'
                tooltip:    'ystools.system_configuration.field.company_logo.tooltip'
                required:   false
                fileConstraints:
                    - Oro\Bundle\AttachmentBundle\Validator\Constraints\Image: ~

        ystools_dtc.company_name:
            data_type: string
            type: Symfony\Component\Form\Extension\Core\Type\TextType
            search_type: text
            priority: 5
            options:
                label:      'ystools.system_configuration.field.company_name.label'
                tooltip:    'ystools.system_configuration.field.company_name.tooltip'
                required:   false

        ystools_dtc.header_footer_bg_color:
            data_type: string
            type: Symfony\Component\Form\Extension\Core\Type\ColorType
            search_type: text
            priority: 95
            options:
                label:      'ystools.system_configuration.field.header_footer_bg_color.label'
                tooltip:    'ystools.system_configuration.field.header_footer_bg_color.tooltip'
                required:   false

        ystools_dtc.header_footer_text_color:
            data_type: string
            type: Symfony\Component\Form\Extension\Core\Type\ColorType
            search_type: text
            priority: 90
            options:
                label:      'ystools.system_configuration.field.header_footer_text_color.label'
                tooltip:    'ystools.system_configuration.field.header_footer_text_color.tooltip'
                required:   false

        ystools_dtc.main_menu_bg_color:
            data_type: string
            type: Symfony\Component\Form\Extension\Core\Type\ColorType
            search_type: text
            priority: 85
            options:
                label:      'ystools.system_configuration.field.main_menu_bg_color.label'
                tooltip:    'ystools.system_configuration.field.main_menu_bg_color.tooltip'
                required:   false

        ystools_dtc.main_menu_text_color:
            data_type: string
            type: Symfony\Component\Form\Extension\Core\Type\ColorType
            search_type: text
            priority: 80
            options:
                label:      'ystools.system_configuration.field.main_menu_text_color.label'
                tooltip:    'ystools.system_configuration.field.main_menu_text_color.tooltip'
                required:   false

        ystools_dtc.secondary_menu_bg_color:
            data_type: string
            type: Symfony\Component\Form\Extension\Core\Type\ColorType
            search_type: text
            priority: 75
            options:
                label:      'ystools.system_configuration.field.secondary_menu_bg_color.label'
                tooltip:    'ystools.system_configuration.field.secondary_menu_bg_color.tooltip'
                required:   false

        ystools_dtc.secondary_menu_text_color:
            data_type: string
            type: Symfony\Component\Form\Extension\Core\Type\ColorType
            search_type: text
            priority: 70
            options:
                label:      'ystools.system_configuration.field.secondary_menu_text_color.label'
                tooltip:    'ystools.system_configuration.field.secondary_menu_text_color.tooltip'
                required:   false

        ystools_dtc.table_header_bg_color:
            data_type: string
            type: Symfony\Component\Form\Extension\Core\Type\ColorType
            search_type: text
            priority: 65
            options:
                label:      'ystools.system_configuration.field.table_header_bg_color.label'
                tooltip:    'ystools.system_configuration.field.table_header_bg_color.tooltip'
                required:   false

        ystools_dtc.table_header_text_color:
            data_type: string
            type: Symfony\Component\Form\Extension\Core\Type\ColorType
            search_type: text
            priority: 60
            options:
                label:      'ystools.system_configuration.field.table_header_text_color.label'
                tooltip:    'ystools.system_configuration.field.table_header_text_color.tooltip'
                required:   false

        ystools_dtc.main_button_bg_color:
            data_type: string
            type: Symfony\Component\Form\Extension\Core\Type\ColorType
            search_type: text
            priority: 55
            options:
                label:      'ystools.system_configuration.field.main_button_bg_color.label'
                tooltip:    'ystools.system_configuration.field.main_button_bg_color.tooltip'
                required:   false

        ystools_dtc.main_button_text_color:
            data_type: string
            type: Symfony\Component\Form\Extension\Core\Type\ColorType
            search_type: text
            priority: 50
            options:
                label:      'ystools.system_configuration.field.main_button_text_color.label'
                tooltip:    'ystools.system_configuration.field.main_button_text_color.tooltip'
                required:   false

        ystools_dtc.secondary_button_bg_color:
            data_type: string
            type: Symfony\Component\Form\Extension\Core\Type\ColorType
            search_type: text
            priority: 45
            options:
                label:      'ystools.system_configuration.field.secondary_button_bg_color.label'
                tooltip:    'ystools.system_configuration.field.secondary_button_bg_color.tooltip'
                required:   false

        ystools_dtc.secondary_button_text_color:
            data_type: string
            type: Symfony\Component\Form\Extension\Core\Type\ColorType
            search_type: text
            priority: 40
            options:
                label:      'ystools.system_configuration.field.secondary_button_text_color.label'
                tooltip:    'ystools.system_configuration.field.secondary_button_text_color.tooltip'
                required:   false

        ystools_dtc.icon_bg_color:
            data_type: string
            type: Symfony\Component\Form\Extension\Core\Type\ColorType
            search_type: text
            priority: 35
            options:
                label:      'ystools.system_configuration.field.icon_bg_color.label'
                tooltip:    'ystools.system_configuration.field.icon_bg_color.tooltip'
                required:   false

        ystools_dtc.icon_content_color:
            data_type: string
            type: Symfony\Component\Form\Extension\Core\Type\ColorType
            search_type: text
            priority: 30
            options:
                label:      'ystools.system_configuration.field.icon_content_color.label'
                tooltip:    'ystools.system_configuration.field.icon_content_color.tooltip'
                required:   false

        ystools_dtc.form_bg_color:
            data_type: string
            type: Symfony\Component\Form\Extension\Core\Type\ColorType
            search_type: text
            priority: 25
            options:
                label:      'ystools.system_configuration.field.form_bg_color.label'
                tooltip:    'ystools.system_configuration.field.form_bg_color.tooltip'
                required:   false

        ystools_dtc.link_color:
            data_type: string
            type: Symfony\Component\Form\Extension\Core\Type\ColorType
            search_type: text
            priority: 20
            options:
                label:      'ystools.system_configuration.field.link_color.label'
                tooltip:    'ystools.system_configuration.field.link_color.tooltip'
                required:   false

        ystools_dtc.font_family:
            data_type: string
            type: Symfony\Component\Form\Extension\Core\Type\ChoiceType
            search_type: choice
            priority: 20
            options:
                label:      'ystools.system_configuration.field.font_family.label'
                tooltip:    'ystools.system_configuration.field.font_family.tooltip'
                required:   false
                placeholder: 'ystools.system_configuration.field.font_family.placeholder'
                choices:
                    'Georgia': georgia
                    'Palatino Linotype': palatino
                    'Times New Roman': times
                    'Arial': arial
                    'Arial Black': arial-black
                    'Comic Sans MS': comic-sans
                    'Impact': impact
                    'Lucida Sans Unicode': lucida
                    'Tahoma': tahoma
                    'Trebuchet MS': trebuchet
                    'Verdana': verdana
                    'Courier New': courier
                    'Lucida Console': lucida-console

    tree:
        system_configuration:
            commerce:
                children:
                    design:
                        children:
                            dtc_default_theme_configuration:
                                priority: -100
                                children:
                                    dtc_logo_configuration:
                                        children:
                                            - ystools_dtc.company_logo
                                            - ystools_dtc.company_name
                                    dtc_ui_main_element_color_configuration:
                                        children:
                                            - ystools_dtc.header_footer_bg_color
                                            - ystools_dtc.header_footer_text_color
                                            - ystools_dtc.table_header_bg_color
                                            - ystools_dtc.table_header_text_color
                                    dtc_ui_secondary_element_color_configuration:
                                        children:
                                            - ystools_dtc.icon_bg_color
                                            - ystools_dtc.icon_content_color
                                            - ystools_dtc.form_bg_color
                                            - ystools_dtc.link_color
                                    dtc_ui_menu_color_configuration:
                                        children:
                                            - ystools_dtc.main_menu_bg_color
                                            - ystools_dtc.main_menu_text_color
                                            - ystools_dtc.secondary_menu_bg_color
                                            - ystools_dtc.secondary_menu_text_color
                                    dtc_ui_button_color_configuration:
                                        children:
                                            - ystools_dtc.main_button_bg_color
                                            - ystools_dtc.main_button_text_color
                                            - ystools_dtc.secondary_button_bg_color
                                            - ystools_dtc.secondary_button_text_color
                                    dtc_ui_additional_styling_configuration:
                                        children:
                                            - ystools_dtc.font_family
